language: cpp
before_install:
 - which g++
 - g++ --version
 - sudo apt-get update
 - sudo apt-get install libeigen3-dev
compiler:
 - gcc
script: 
 - cd workspace/Analysis/FastSLAM/FastSLAM1_0/
 - qmake -project
 - qmake
 - make
